export const DBACTIONS = {
  GET_ALBUMS_FROM_DATABASE: '[DB ACTION]: GET ALBUMS FROM DATABASE',
  GET_ARTISTS_FROM_DATABASE: '[DB ACTION]: GET ARTISTS FROM DATABASE',
  GET_PLAYLISTS_FROM_DATABASE: '[DB ACTION}: GET PLAYLISTS FROM DATABASE',
  SET_ARTISTS_NEXT_PAGE: '[DB ACTION]: SET ARTISTS NEXT PAGE',
  SET_ALBUMS_NEXT_PAGE: '[DB ACTION]: SET ALBUMS NEXT PAGE',
  SET_PLAYLISTS_NEXT_PAEG: '[DB ACTION]: SET PLAYLISTS NEXT PAGE',
  SET_NEXT_PAGE: '[DB ACTION}: SET NEXT PAGE',
  GET_ITEMS_FROM_DATABASE: '[DB ACTION]: GET ITEMS FROM DATABASE'
}
