export const DBACTIONS = {
  GET_ALBUMS_FROM_DATABASE: '[DB ACTION]: GET ALBUMS FROM DATABASE',
  GET_ARTISTS_FROM_DATABASE: '[DB ACTION]: GET ARTISTS FROM DATABASE',
  GET_PLAYLISTS_FROM_DATABASE: '[DB ACTION}: GET PLAYLISTS FROM DATABASE',
  GET_TRACKS_FROM_DATABASE: '[DB ACTION}: GET PLAYLISTS FROM DATABASE',
  SET_ARTISTS_NEXT_PAGE: '[DB ACTION]: SET ARTISTS NEXT PAGE',
  SET_ALBUMS_NEXT_PAGE: '[DB ACTION]: SET ALBUMS NEXT PAGE',
  SET_PLAYLISTS_NEXT_PAEG: '[DB ACTION]: SET PLAYLISTS NEXT PAGE',
  SET_NEXT_PAGE: '[DB ACTION}: SET NEXT PAGE',
  GET_ITEMS_FROM_DATABASE: '[DB ACTION]: GET ITEMS FROM DATABASE',
  SET_CURRENT_TRACK: '[DB ACTION]: SET CURRENT TRACK',
  SET_SEARCH: '[DB ACTION]: SET SEARCH',
  SET_SEARCH_RESULTS: '[DB ACTION] SET SEARCH RESULTS',
  SET_INITIAL_STATE: '[DB ACTION] SET INITIAL STATE',
  SET_ACTIVE_DROPDOWN: '{UI ACTION] SET ACTIVE DROPDOW',
  SET_BIG_PLAYER_UI: '{UI ACTION] SET BIG PLAYER UI'
}
