export const PLAYERACTIONS = {
  SET_CURRENT_SONG: '[PLAYER_ACTION]: SET CURRENT SONG',
  SET_PAUSED_SONG: '[PLAYER_ACTION] SET PAUSED SONG STATE',
  SET_CURRENT_TIME: '[PLAYER_ACTION] SET CURRENT TRACK TIME'
}
